### ISSUE TITLE
[QUESTION] Embedding and Ranking

### ISSUE THREAD

**Issue by zeyaddeeb** [online-ml/deep-river#88]
If I have a model like this:
```python
class Model(torch.nn.Module):
...
        self.user_embed = torch.nn.Embedding(n_users, n_factors)
...
```

What would be the best way to implement `def learn_one...` given that new users get added from a stream?

**Comment by kulbachcedric** [comment]
Hi @zeyaddeeb,
I would stick to the regression learn_one method: 

`    
def learn_one(self, x: dict, y: RegTarget, **kwargs) -> "Regressor":
        if not self.module_initialized:
            self.kwargs["n_features"] = len(x)
            self.initialize_module(**self.kwargs)
        x_t = dict2tensor(x, self.device)
        y_t = float2tensor(y, device=self.device)
        self._learn(x_t, y_t)
        return self`

The helper methods _learn, dict2tensor and float2tensor might help you as well. 

Best
Cedric
