### ISSUE TITLE
conceptual drift and catastrophic forgetting

### ISSUE THREAD

**Issue by panchao12345** [online-ml/deep-river#89]
Hello, how does deep-river address conceptual drift and catastrophic forgetting?

**Comment by kulbachcedric** [comment]
Hi @panchao12345,
that's a really nice question. 
Deep river is kind of a tool box for implementing nn within the river API. 
However, conceptual drifts and catastrophic forgetting are not handled specifically within this framework as the needs are quite different from case to case. One approach we played around with, was to adapt the underlying optimizer, but the default optimizers such as Adam are already quite suitable for learning on data streams.

Best
Cedric

**Comment by panchao12345** [comment]
@kulbachcedric     Can the current deep-river library perform online learning of dynamic models for autonomous systems, such as a quadcopter?

**Comment by panchao12345** [comment]
@kulbachcedric，  One more question: Are there any tutorial videos for deep-river? Please provide a link.

**Comment by kulbachcedric** [comment]
Hi @panchao12345 
what do you mean by dynamic models? In which sense do you need them to be dynamic? 
We held a tutorial last year at ECML and @hoanganhngo610 and @lucasczz concluded it very nicely within this [paper](https://arxiv.org/abs/2405.17222).

Best
Cedric

**Comment by panchao12345** [comment]
@kulbachcedric    
The quadcopter dynamic model is the mathematical model of its motion. Given the current state, velocity, and control inputs, the next state can be predicted based on the learned mathematical model. The model is as depicted in the figure.  
![1111](https://github.com/user-attachments/assets/c1153efe-148e-4612-bc8e-5ef7ba256490)

**Comment by kulbachcedric** [comment]
Hi @panchao12345,
For me it seems to be a multi target regression problem to be solved, which generally can be solved with river. Could you provide an example?
Best 
Cedric
