### ISSUE TITLE
multiple inputs and multiple predicted outputs

### ISSUE THREAD

**Issue by panchao12345** [online-ml/deep-river#90]
Is it possible for deep-river to take multiple inputs to a learned model and output multiple predicted outputs? For example tensorflow1 of the form 
model_output = self.sess.run([self.curr_nn_output], feed_dict={self.x_: inputs_list})，where inputs_list and model_output are 2-dimensional lists .

**Comment by kulbachcedric** [comment]
Hi @panchao12345 

deep-river only supports PyTorch as PyTorch is much faster in adapting the underlying architecture in an online manner and when it come to iterative learning. the river API supports multiple inputs as well as multiple output. 

Best
Cedric

**Comment by panchao12345** [comment]
@kulbachcedric   Thank you very much for your reply.  This code runs a TensorFlow session to process a 2D input array using the current neural network model. Each row of the input array represents a separate input sample, and the model generates one output for each row simultaneously. The results are stored in the `model_output` variable.  Could deep-river implement this functionality without using predict_one() to perform loop iteration? Because the loop iteration of predict_one() takes a lot of time.

**Comment by kulbachcedric** [comment]
Hi @panchao12345 
Unfortunately tensor flow is not supported within deep-river. However, the input needs to follow the river API in the sense that it needs to be a flat dictionary. If I understood correctly this is the case in your scenario. The deep-river has also the predict_many method that predicts on many instances in a much more efficient way.

Best Cedric
