### ISSUE TITLE
Predict_one is not working

### ISSUE THREAD

**Issue by leal2020** [online-ml/deep-river#91]
First of all, congratulations. Great work.

In example_rnn_regression.ipynb there is an error in Cell 5
1it [00:01,  1.02s/it]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 2
      1 for x, y in tqdm(dataset.take(5000)):
----> 2     y_pred = model_pipeline.predict_one(x)
      3     metric = metric.update(y_true=y, y_pred=y_pred)
      4     model_pipeline = model_pipeline.learn_one(x=x, y=y)

AttributeError: 'NoneType' object has no attribute 'predict_one'
I think the error is on RollingRegressor

Thanks

**Comment by kulbachcedric** [comment]
Hi @leal2020 
Thanks 🙏 
You are totally right! 
I just fixed it :-) 

Best 
Cedric
